AWSTemplateFormatVersion: 2010-09-09
Description: VPC con subred publica e Instancia EC2 Condicional

Parameters:
  AmiID:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Description: "The ID of the AMI."
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  CrearInstancia:
    Description: Indica si se debe crear la instancia EC2
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    ConstraintDescription: Solo se permite true o false
  EC2InstanceType:
    Type: String
    Description: Tipo de instancia EC2
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium

Conditions:
  CreateInstance: !Equals [!Ref CrearInstancia, "true"]
  NotCreateInstance: !Equals [!Ref CrearInstancia, "false"]
Rules:
  ValidateInstanceType:
    RuleCondition: !Equals [!Ref CrearInstancia, "true"]
    Assertions:
      - AssertDescription: "El tipo de instancia debe ser t2.micro, t2.small o t2.medium"
        Assert: !Contains
          - - t2.micro
            - t2.small
            - t2.medium
          - !Ref EC2InstanceType

Resources:
  VPCInstance:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-VPC"

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCInstance
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: !Select [0, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-PublicSubnet"

  EC2Instance:
    Type: AWS::EC2::Instance
    Condition: CreateInstance
    Properties:
      ImageId: !Ref AmiID
      InstanceType: !Ref EC2InstanceType
      SubnetId: !Ref PublicSubnet
      Tags:
        - Key: Name
          Value:
            !Join ["-", [!Ref "AWS::Region", !Ref "AWS::StackName", "ricardo"]]
        - Key: VPCID
          Value: !GetAtt PublicSubnet.VpcId
