# 1. AWSTemplateFormatVersion
# Versión obligatoria del esquema.
AWSTemplateFormatVersion: '2010-09-09'

# 2. Transform
# Usamos la transformación Serverless para incluir una pequeña función Lambda
# que podría servir para auditar accesos o rotar claves (justificando el uso de esta sección).
Transform: AWS::Serverless-2016-10-31

# 3. Description
Description: >
  Arquitectura segura de Bastion Host. Despliega una VPC con subredes públicas y privadas.
  El acceso SSH a la instancia privada solo se permite desde el Bastion.

# 4. Metadata
# Organiza los parámetros visualmente en la consola de AWS.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Configuración de Red y Entorno"
        Parameters:
          - Environment
          - VpcCidr
      - Label:
          default: "Seguridad y Accesos"
        Parameters:
          - KeyPairName
          - AllowedSSHLocation

# 5. Parameters
Parameters:
  Environment:
    Description: Define el entorno (Prod requiere IP específica, Dev permite 0.0.0.0/0 con advertencia).
    Type: String
    Default: Dev
    AllowedValues: [Dev, Prod]

  VpcCidr:
    Description: Rango IP para la VPC.
    Type: String
    Default: 10.10.0.0/16

  AllowedSSHLocation:
    Description: Rango de IPs permitido para acceder al Bastion (ej. tu IP pública/32).
    Type: String
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Debe ser un CIDR válido (x.x.x.x/x).

  KeyPairName:
    Description: Nombre de un par de claves existente en EC2.
    Type: AWS::EC2::KeyPair::KeyName

# 6. Rules
# Regla de Gobernanza: Si es Producción, PROHIBIDO abrir el SSH a todo el mundo (0.0.0.0/0).
Rules:
  SecureAccessInProd:
    RuleCondition: !Equals [!Ref Environment, "Prod"]
    Assertions:
      - Assert: !Not [!Equals [!Ref AllowedSSHLocation, "0.0.0.0/0"]]
        AssertDescription: "EN PRODUCCIÓN NO SE PERMITE ACCESO SSH DESDE 0.0.0.0/0. ESPECIFICA TU IP."

# 7. Mappings
# Mapeo de AMIs (Amazon Linux 2023) según región y tamaño de instancia según entorno.
Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0c7217cdde317cfec
    eu-west-1:
      AMI: ami-0694d931cee176e7d
    # Nota: Estos IDs cambian con el tiempo, verificar antes de desplegar.
  
  InstanceSizeConfig:
    Dev:
      Type: t2.nano
    Prod:
      Type: t2.micro

# 8. Conditions
# Solo crearemos una IP Elástica (EIP) fija para el Bastion si estamos en Producción.
Conditions:
  IsProduction: !Equals [!Ref Environment, "Prod"]

# 9. Resources
Resources:
  # --- RED (VPC, Subredes, IGW) ---
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags: [{Key: Name, Value: !Sub "BastionVPC-${Environment}"}]

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Select [0, !Cidr [!Ref VpcCidr, 2, 8]] # Crea 10.10.0.0/24
      MapPublicIpOnLaunch: true
      Tags: [{Key: Name, Value: Public-Subnet}]

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Select [1, !Cidr [!Ref VpcCidr, 2, 8]] # Crea 10.10.1.0/24
      Tags: [{Key: Name, Value: Private-Subnet}]

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: GatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # --- SEGURIDAD ---
  # 1. Bastion SG: Acepta tráfico desde Internet (limitado por AllowedSSHLocation)
  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG para Bastion Host
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowedSSHLocation

  # 2. Private SG: SOLO acepta tráfico desde el Bastion SG (Security Chaining)
  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG para Instancia Privada
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref BastionSecurityGroup # Referencia al SG, no a una IP

  # --- INSTANCIAS ---
  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !FindInMap [InstanceSizeConfig, !Ref Environment, Type]
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      KeyName: !Ref KeyPairName
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds: [!Ref BastionSecurityGroup]
      Tags: [{Key: Name, Value: Bastion-Host}]

  PrivateWorkload:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !FindInMap [InstanceSizeConfig, !Ref Environment, Type]
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      KeyName: !Ref KeyPairName
      SubnetId: !Ref PrivateSubnet
      SecurityGroupIds: [!Ref PrivateSecurityGroup]
      Tags: [{Key: Name, Value: Private-Server}]

  # --- EXTRAS CONDICIONALES Y TRANSFORM ---
  
  # IP Elástica (Solo en Prod)
  BastionEIP:
    Type: AWS::EC2::EIP
    Condition: IsProduction
    Properties:
      InstanceId: !Ref BastionHost

  # Lambda (Justificando 'Transform')
  AuditFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      InlineCode: |
        exports.handler = async (event) => {
          console.log("Auditoría: Nuevo despliegue de Bastion detectado.");
        };

# 10. Outputs
Outputs:
  BastionPublicIP:
    Description: IP pública para conectar al Bastion.
    # Si es Prod devuelve la EIP, si es Dev devuelve la IP pública dinámica.
    Value: !If [IsProduction, !Ref BastionEIP, !GetAtt BastionHost.PublicIp]
  
  PrivateInstanceIP:
    Description: IP privada del servidor interno (accesible solo desde Bastion).
    Value: !GetAtt PrivateWorkload.PrivateIp
  
  SSHCommand:
    Description: Comando para conectar (Agent Forwarding recomendado).
    Value: !Sub "ssh -A -J ec2-user@${BastionHost.PublicDnsName} ec2-user@${PrivateWorkload.PrivateIp}"