AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Environment:
    Description: Defines environment type
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - beta
      - prod
    ConstraintDescription: Use valid environment [dev, qa, beta, prod]

Conditions:
  IsProd: !Equals [!Ref Environment, prod]

  IsLab: !Or
    - !Equals [!Ref Environment, dev]
    - !Equals [!Ref Environment, qa]
    - !Equals [!Ref Environment, beta]

  IsLab2: !Not
    - !Equals [!Ref Environment, prod]

  IsLab3: !Not
    - !Condition IsProd

Resources:
  ProdBucket:
    Type: AWS::S3::Bucket
    Condition: IsProd

  LabBucket:
    Type: AWS::S3::Bucket
    Condition: IsLab


