AWSTemplateFormatVersion: '2010-09-09'

Description: >
  Infraestructura de red con VPC, subredes públicas/privadas, NAT y VPC Peering.
  Utiliza Mappings para definir CIDRs según el entorno.

Parameters:
  Environment:
    Description: Seleccione el entorno para configurar los rangos CIDR.
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Prod

  TargetVpcId:
    Description: ID de ejemplo de la VPC destino para realizar el VPC Peering 
    Type: String
    Default: vpc-12345678

Mappings:
  NetworkConfig:
    Dev:
      PublicSubnet1: 20.0.1.0/24
      PublicSubnet2: 20.0.2.0/24
      PrivateSubnet1: 20.0.10.0/24
      PrivateSubnet2: 20.0.11.0/24
    Prod:
      PublicSubnet1: 20.0.100.0/24
      PublicSubnet2: 20.0.101.0/24
      PrivateSubnet1: 20.0.200.0/24
      PrivateSubnet2: 20.0.201.0/24
Resources:
  # 1. VPC
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 20.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "VPC-${Environment}"

  # 2. Internet Gateway (IGW) y Adjunto
  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref InternetGateway

  # 3. Subredes Públicas (Diferentes AZs)
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !FindInMap [NetworkConfig, !Ref Environment, PublicSubnet1]
      AvailabilityZone: !Select [0, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Public-Subnet-1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !FindInMap [NetworkConfig, !Ref Environment, PublicSubnet2]
      AvailabilityZone: !Select [1, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Public-Subnet-2

  # Tabla de Rutas Pública (Hacia IGW)
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1Assoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2Assoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  # NAT Gateway (Ubicado en Subred Pública 1)
  NatGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayEIP.AllocationId
      SubnetId: !Ref PublicSubnet1

  # Subredes Privadas (Diferentes AZs)
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !FindInMap [NetworkConfig, !Ref Environment, PrivateSubnet1]
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: Private-Subnet-1

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !FindInMap [NetworkConfig, !Ref Environment, PrivateSubnet2]
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Name
          Value: Private-Subnet-2

  #Tabla de Rutas Privada (Hacia NAT GW)
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway

  PrivateSubnet1Assoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnet2Assoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable

  VPCPeering:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId: !Ref MyVPC
      PeerVpcId: !Ref TargetVpcId
      Tags:
        - Key: Name
          Value: Peering-Connection

Outputs:
  VpcID:
    Description: ID de la VPC creada
    Value: !Ref MyVPC
  
  NatGatewayID:
    Description: ID del NAT Gateway
    Value: !Ref NatGateway
  
  PublicSubnets:
    Description: IDs de las subredes públicas
    Value: !Join [",", [!Ref PublicSubnet1, !Ref PublicSubnet2]]
  
  PrivateSubnets:
    Description: IDs de las subredes privadas
    Value: !Join [",", [!Ref PrivateSubnet1, !Ref PrivateSubnet2]]